/**
 * Phase 00 · Worker Loader spike — Task 7
 *
 * The binding-injection shape Phase 09 will generate `.d.ts` against.
 *
 * Phase 09 runs this from inside RunDO, so the spike does too: `ctx.exports`
 * lives on DurableObjectState, and testing it from a plain Worker would prove
 * something we are not going to do.
 */
import { DurableObject, RpcTarget, WorkerEntrypoint } from "cloudflare:workers";

/**
 * `Env` is generated by `wrangler types` into worker-configuration.d.ts and is
 * global. SPIKE_SECRET comes from .dev.vars locally and `wrangler secret put`
 * in production; its value is never in the repo.
 */

const ISOLATE_COMPAT_DATE = "2026-08-01";

/**
 * A capability the isolate is allowed to hold.
 *
 * The secret lives on the parent's `env` and is used here; only a DERIVED value
 * crosses the boundary. Identity travels in `props`, so the isolate never
 * states who it is acting as and therefore cannot claim to be someone else.
 */
export class SecretBinding extends WorkerEntrypoint<
  Env,
  { runId: string; onDutyUserId: string }
> {
  /** Who this binding acts as — read from props, never from an argument. */
  async whoAmI(): Promise<string> {
    return this.ctx.props.onDutyUserId;
  }

  /** Uses the secret; returns a derived value that does not reveal it. */
  async sign(message: string): Promise<string> {
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(this.env.SPIKE_SECRET),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"],
    );
    const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
    return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
  }

  /**
   * Deliberate control: an intentionally leaky method. If the isolate CAN read
   * the secret through a method that hands it over, that is expected and proves
   * nothing. What matters is that no OTHER path reaches it. Present so the
   * findings can say the probe was capable of detecting a leak.
   */
  async __leakControl(): Promise<string> {
    return this.env.SPIKE_SECRET;
  }
}

/**
 * MEASURED, and it does NOT match inspired-from-ronit.md §4.
 *
 * §4 says raw DO stubs cannot cross and RpcTarget subclasses can. On
 * workerd 1.20260801.1 the split is by PLACEMENT, not by type:
 *
 *   on `env`            RpcTarget -> DataCloneError at LOADER.load()
 *                       raw DO stub -> crosses, and is callable
 *   as a call argument  RpcTarget -> works
 *
 * §4 is about `entrypoint.run(facet)` — an argument — so both are true of
 * different boundaries. Phase 09 must not put an RpcTarget on `env`.
 */
export class RunBridge extends RpcTarget {
  #do: SpikeDO;
  constructor(target: SpikeDO) {
    super();
    this.#do = target;
  }
  async escalate(draft: unknown, why: string): Promise<{ status: string; why: string }> {
    return this.#do.recordEscalation(draft, why);
  }
  async turnCount(): Promise<number> {
    return this.#do.turnCount();
  }
}

/**
 * Variant A: an RpcTarget holding NO stub at all, only plain state.
 * Isolates whether the failure is about RpcTarget itself or about what it holds.
 */
export class PlainBridge extends RpcTarget {
  #note: string;
  constructor(note: string) {
    super();
    this.#note = note;
  }
  async echo(msg: string): Promise<string> {
    return `${this.#note}:${msg}`;
  }
}

/**
 * Variant B: the shape the plan actually specifies — an RpcTarget wrapping a
 * DurableObjectStub, not the DurableObject instance.
 */
export class StubBridge extends RpcTarget {
  #run: DurableObjectStub;
  constructor(run: DurableObjectStub) {
    super();
    this.#run = run;
  }
  async turnCount(): Promise<number> {
    return (this.#run as unknown as { turnCount(): Promise<number> }).turnCount();
  }
}

/** What the isolate reports back about its own environment. */
type Probe = {
  envKeys: string[];
  bindingShapes: Record<string, string>;
  secretFound: string | null;
  attempts: Array<{ label: string; outcome: string; detail?: string; error?: string }>;
};

/**
 * Named separately so callers can annotate the stub without going through
 * `DurableObjectNamespace<SpikeDO>`: the generated Env references SpikeDO, and
 * SpikeDO extends DurableObject<Env>, so inference through the namespace
 * collapses to `never`. Phase 08 will hit this too.
 */
export type ProbeResult = {
  ok: boolean;
  probe?: Probe;
  signed?: string;
  identity?: string;
  bridgeEscalate?: unknown;
  error?: string;
  failedStep?: string;
  serializability?: Record<string, string>;
};

export class SpikeDO extends DurableObject<Env> {
  #escalations: Array<{ draft: unknown; why: string }> = [];

  async recordEscalation(draft: unknown, why: string) {
    this.#escalations.push({ draft, why });
    return { status: "awaiting_approval", why };
  }

  async turnCount(): Promise<number> {
    return this.#escalations.length;
  }

  /**
   * Task 7: binding injection, identity-via-props, and the exfiltration probe.
   *
   * `includeList` selects which capability shapes go on the isolate's `env`:
   * secret | run | plain | stubbridge | raw | argbridge. One at a time, because
   * a single DataCloneError at load() takes the whole run with it and tells you
   * nothing about which member caused it.
   */
  async probe(includeList: string[]): Promise<ProbeResult> {
    const include = new Set(includeList);
    const runId = "run_spike_0001";
    const onDutyUserId = "U_ONDUTY_ALICE";

    // Every step is inside the guard: a throw during env construction or
    // LOADER.load surfaces at the CALLER of this RPC method, which reads as a
    // Worker-level failure and hides where it actually came from.
    let step = "construct-env";
    try {
    const env: Record<string, unknown> = {
      // A plain serializable value, to show what ordinary data looks like.
      RUN_ID: runId,
    };

    // Bisected one at a time: LOADER.load() throws DataCloneError for at least
    // one of these, and "which one" is the finding Phase 09 needs.
    if (include.has("secret")) {
      // The canonical construction shape (§3). NOT a raw service binding.
      env.SECRET = this.ctx.exports.SecretBinding({ props: { runId, onDutyUserId } });
    }
    if (include.has("run")) {
      // The DO reach-back, wrapped in an RpcTarget (§4).
      env.RUN = new RunBridge(this);
    }
    if (include.has("plain")) {
      env.PLAIN = new PlainBridge("bridge");
    }
    if (include.has("stubbridge")) {
      env.STUB_BRIDGE = new StubBridge(
        this.env.SPIKE_DO.get(this.env.SPIKE_DO.idFromName("stub-bridge-target")),
      );
    }
    if (include.has("raw")) {
      // Predicted to fail at the marshalling boundary.
      env.RAW_DO = this.env.SPIKE_DO.get(this.env.SPIKE_DO.idFromName("raw-stub-probe"));
    }

    step = "loader-load";
    const stub = this.env.LOADER.load({
      compatibilityDate: ISOLATE_COMPAT_DATE,
      compatibilityFlags: ["nodejs_compat"],
      mainModule: "main.js",
      modules: { "main.js": PROBE_MODULE },
      globalOutbound: null,
      env,
    });

    try {
      const entrypoint = stub.getEntrypoint() as unknown as {
        run(): Promise<{
          probe: Probe;
          signed: string;
          identity: string;
          bridgeEscalate: unknown;
        }>;
      };
      // §4's claim is about passing an RpcTarget as an ARGUMENT to run(), which
      // is a different boundary from placing it on `env`. Tested separately so
      // the two can be reported apart rather than conflated.
      let rpcTargetAsArgument = "not attempted";
      if (include.has("argbridge")) {
        try {
          const viaArg = await (
            entrypoint as unknown as { runWithBridge(b: unknown): Promise<unknown> }
          ).runWithBridge(new PlainBridge("arg"));
          rpcTargetAsArgument = `ok: ${JSON.stringify(viaArg)}`;
        } catch (err) {
          rpcTargetAsArgument = `threw: ${String(err)}`;
        }
      }

      const result = await entrypoint.run();
      (result as Record<string, unknown>).rpcTargetAsArgument = rpcTargetAsArgument;

      // The value coming back from the isolate can itself contain RPC
      // references, which throw only when they cross the NEXT boundary
      // (DO -> Worker). Find out which field, rather than guessing.
      const serializability: Record<string, string> = {};
      const safe: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(result ?? {})) {
        try {
          structuredClone(value);
          serializability[key] = "cloneable";
          safe[key] = value;
        } catch (err) {
          // Must be DROPPED, not merely labelled: returning it would throw on
          // the DO -> Worker hop and take the diagnostic down with it.
          serializability[key] = `NOT cloneable: ${String(err)}`;
        }
      }

      return { ok: true, ...safe, serializability };
    } catch (err) {
      return { ok: false, error: String(err), failedStep: "isolate-run" };
    }
    } catch (err) {
      return { ok: false, error: String(err), failedStep: step };
    }
  }
}

/**
 * Runs INSIDE the isolate. Enumerates everything reachable and tries to walk
 * its way to the secret. Every attempt is caught individually so the inventory
 * is complete rather than truncated at the first throw.
 */
const PROBE_MODULE = `
  import { WorkerEntrypoint } from "cloudflare:workers";

  async function attempt(label, fn) {
    try { return { label, outcome: "ok", detail: String(await fn()) }; }
    catch (err) { return { label, outcome: "threw", error: String(err) }; }
  }

  const SECRET_HINTS = ["SPIKE_SECRET", "secret", "SECRET_VALUE"];

  export default class extends WorkerEntrypoint {
    /** Receives an RpcTarget as a call ARGUMENT rather than on env. */
    async runWithBridge(bridge) {
      return { echoed: await bridge.echo("hello") };
    }

    async run() {
      const env = this.env ?? {};
      const envKeys = Object.keys(env);

      const bindingShapes = {};
      for (const k of envKeys) {
        const v = env[k];
        bindingShapes[k] = v === null ? "null" : typeof v;
      }

      const attempts = [];
      let secretFound = null;

      // 1. Is the raw secret sitting on env under any obvious name?
      for (const hint of SECRET_HINTS) {
        if (typeof env[hint] === "string") secretFound = env[hint];
      }

      // 2. Walk the binding object's own and inherited properties.
      attempts.push(await attempt("enumerate-SECRET-props", async () => {
        const own = Object.getOwnPropertyNames(env.SECRET ?? {});
        const proto = Object.getOwnPropertyNames(Object.getPrototypeOf(env.SECRET ?? {}) ?? {});
        return JSON.stringify({ own, proto });
      }));

      // 3. Try to reach the parent's env through the stub.
      attempts.push(await attempt("SECRET.env", async () => JSON.stringify(env.SECRET?.env)));
      attempts.push(await attempt("SECRET.ctx", async () => JSON.stringify(env.SECRET?.ctx)));
      attempts.push(await attempt("SECRET.SPIKE_SECRET", async () => String(env.SECRET?.SPIKE_SECRET)));

      // Property access returns a lazy JsRpcProperty rather than throwing, so
      // the real attack is AWAITING it. These are the ones that matter.
      attempts.push(await attempt("await SECRET.SPIKE_SECRET", async () => await env.SECRET.SPIKE_SECRET));
      attempts.push(await attempt("await SECRET.env", async () => await env.SECRET.env));
      attempts.push(await attempt("await SECRET.env.SPIKE_SECRET", async () => await env.SECRET.env.SPIKE_SECRET));
      attempts.push(await attempt("await SECRET.ctx.props", async () => JSON.stringify(await env.SECRET.ctx.props)));

      // 4. Can the isolate forge its own identity by passing one?
      attempts.push(await attempt("whoAmI-no-args", async () => await env.SECRET.whoAmI()));
      attempts.push(await attempt("whoAmI-spoof-attempt", async () => await env.SECRET.whoAmI("U_SOMEONE_ELSE")));

      // 5. The leak control — proves the probe could see a secret if one crossed.
      attempts.push(await attempt("leak-control", async () => {
        const v = await env.SECRET.__leakControl();
        secretFound = secretFound ?? v;
        return "returned " + String(v).length + " chars";
      }));

      // 6. The RpcTarget reach-back.
      const bridgeEscalate = await (async () => {
        try { return await env.RUN.escalate({ text: "draft" }, "needs a human"); }
        catch (err) { return { error: String(err) }; }
      })();

      // 7. Raw DO stub, when present.
      if ("RAW_DO" in env) {
        attempts.push(await attempt("raw-do-stub-call", async () => await env.RAW_DO.turnCount()));
      }

      const signed = await env.SECRET.sign("hello");
      const identity = await env.SECRET.whoAmI();

      return {
        probe: { envKeys, bindingShapes, secretFound, attempts },
        signed,
        identity,
        bridgeEscalate,
      };
    }
  }
`;
